import {
  Bot, FileText, Package, ShoppingBag, MessageSquare,
  FileCheck, Users, Truck, AlertTriangle, BarChart3,
  type LucideIcon,
} from "lucide-react";

export type AgentConfig = {
  id: string;
  nom: string;
  icon: LucideIcon;
  description: string;
  mission: string;
  service: string;
  statut: "Actif" | "Désactivé";
  sourcesCount: number;
  docsCount: number;
  maj: string;
  responsable: string;
  readiness: number;
  autonomie: "Suggestions uniquement" | "Validation humaine obligatoire" | "Actions automatiques limitées";
  langue: string;
  ton: string;
  actions: { label: string; enabled: boolean }[];
  instructions: string;
  obligatoires: string[];
  restrictions: string[];
  connaissances: { nom: string; type: string; categorie: string; date: string; maj: string; statut: string; partage: "Privée" | "Partagée" | "Générale" }[];
  sources: { nom: string; description: string; statut: "Connecté" | "Non connecté" | "Synchronisation nécessaire" }[];
  questionsSuggerees: string[];
  reponseTest: {
    question: string;
    contenu: string[];
    sourcesUsed: string[];
    confiance: number;
    manquantes: string[];
    actions: string[];
  };
};

export const AGENTS: AgentConfig[] = [
  {
    id: "technico",
    nom: "Agent technico-commercial",
    icon: Bot,
    description: "Assiste les commerciaux dans la recommandation de produits techniques.",
    mission: "Analyser les besoins techniques des clients et recommander les produits SERIMA les plus adaptés.",
    service: "Direction commerciale",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 42,
    maj: "24/07/2026",
    responsable: "M. Lefèvre",
    readiness: 92,
    autonomie: "Validation humaine obligatoire",
    langue: "Français",
    ton: "Professionnel et technique",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Proposer une recommandation", enabled: true },
      { label: "Générer une réponse", enabled: true },
      { label: "Préparer un devis", enabled: false },
      { label: "Transférer une demande", enabled: true },
    ],
    instructions:
      "Analyser précisément le besoin technique exprimé par le client (utilisation, contraintes, environnement). Consulter systématiquement le catalogue produits SERIMA et les fiches techniques. Proposer une référence principale et une alternative. Justifier chaque recommandation par au moins deux critères techniques. Ne jamais confirmer une compatibilité sans source vérifiée.",
    obligatoires: ["Type d'utilisation", "Famille de produit", "Matière", "Dimensions", "Quantité", "Contraintes techniques"],
    restrictions: [
      "Ne jamais inventer une référence produit",
      "Ne pas confirmer un prix sans consulter les données disponibles",
      "Demander une validation humaine en cas de doute",
      "Signaler toutes les informations manquantes",
      "Indiquer clairement lorsqu'une information n'est pas disponible",
    ],
    connaissances: [
      { nom: "Catalogue produits SERIMA 2026", type: "PDF", categorie: "Catalogue produit", date: "12/01/2026", maj: "20/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Fiches techniques Hardox", type: "PDF", categorie: "Fiche technique", date: "03/03/2026", maj: "18/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Nuances et matériaux", type: "Excel", categorie: "Fiche technique", date: "22/02/2026", maj: "10/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Normes industrielles EN 10025", type: "PDF", categorie: "Certificat", date: "05/04/2026", maj: "05/04/2026", statut: "À vérifier", partage: "Générale" },
      { nom: "Compatibilités produits", type: "Excel", categorie: "Procédure interne", date: "14/05/2026", maj: "23/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Références alternatives", type: "Word", categorie: "Procédure interne", date: "01/06/2026", maj: "17/07/2026", statut: "En traitement", partage: "Partagée" },
    ],
    sources: [
      { nom: "Catalogue SERIMA", description: "Catalogue produits complet", statut: "Connecté" },
      { nom: "ERP", description: "Données produits et disponibilités", statut: "Connecté" },
      { nom: "Documents internes", description: "Fiches et procédures", statut: "Connecté" },
      { nom: "E-mails", description: "Demandes clients entrantes", statut: "Synchronisation nécessaire" },
      { nom: "CRM", description: "Historique client", statut: "Connecté" },
      { nom: "WhatsApp", description: "Messages entrants", statut: "Non connecté" },
    ],
    questionsSuggerees: [
      "Quelle tôle recommander pour une utilisation dans une carrière avec une forte abrasion ?",
      "Quel inox utiliser pour une application alimentaire ?",
      "Quelle alternative à un profilé HEA 200 non disponible ?",
    ],
    reponseTest: {
      question: "Quelle tôle recommander pour une utilisation dans une carrière avec une forte abrasion ?",
      contenu: [
        "Produit recommandé : Tôle Hardox 450, épaisseur 8 mm",
        "Caractéristiques : dureté 450 HBW, résistance à l'abrasion élevée",
        "Justification : matériau conçu pour environnements très abrasifs (extraction, carrières)",
        "Alternative : Hardox 500 pour abrasion extrême",
        "Disponibilité fictive : 12 tôles en stock à Lyon",
      ],
      sourcesUsed: ["Catalogue produits 2026", "Fiche technique anti-abrasion", "Tableau des disponibilités"],
      confiance: 87,
      manquantes: ["Dimensions exactes souhaitées", "Volume annuel prévisionnel"],
      actions: ["Préparer un devis", "Transférer au commercial référent"],
    },
  },
  {
    id: "devis",
    nom: "Agent de traitement des devis",
    icon: FileText,
    description: "Extrait les informations des demandes et prépare des brouillons de devis.",
    mission: "Analyser les demandes reçues sur tous les canaux et générer un brouillon de devis prêt à valider.",
    service: "Administration des ventes",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 31,
    maj: "23/07/2026",
    responsable: "Mme Bernard",
    readiness: 88,
    autonomie: "Validation humaine obligatoire",
    langue: "Français",
    ton: "Formel et précis",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Préparer un devis", enabled: true },
      { label: "Générer une réponse", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Créer une alerte", enabled: true },
      { label: "Transférer une demande", enabled: true },
    ],
    instructions:
      "Extraire références, dimensions, quantités et conditions commerciales de chaque demande reçue. Vérifier la disponibilité des produits et appliquer les conditions tarifaires en vigueur. Signaler toute ambiguïté (dimension incomplète, référence introuvable). Générer un brouillon structuré : sous-total HT, TVA, total TTC, conditions de paiement et validité.",
    obligatoires: ["Client", "Références produit", "Quantités", "Dimensions", "Délai souhaité", "Adresse de livraison"],
    restrictions: [
      "Ne pas envoyer un devis sans validation commerciale",
      "Ne jamais appliquer une remise supérieure au seuil autorisé",
      "Signaler les références introuvables",
      "Ne pas inventer un prix",
    ],
    connaissances: [
      { nom: "Catalogue tarifaire 2026", type: "Excel", categorie: "Catalogue produit", date: "02/01/2026", maj: "22/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Conditions commerciales", type: "PDF", categorie: "Procédure interne", date: "15/01/2026", maj: "10/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Modèles de devis", type: "Word", categorie: "Procédure interne", date: "08/02/2026", maj: "08/02/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Remises autorisées", type: "Excel", categorie: "Procédure interne", date: "12/03/2026", maj: "20/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Conditions de paiement", type: "PDF", categorie: "Procédure interne", date: "04/04/2026", maj: "04/04/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Délais de livraison", type: "Excel", categorie: "Données ERP fictives", date: "18/05/2026", maj: "23/07/2026", statut: "En traitement", partage: "Partagée" },
    ],
    sources: [
      { nom: "ERP", description: "Prix, stocks, clients", statut: "Connecté" },
      { nom: "CRM", description: "Fiches et historique client", statut: "Connecté" },
      { nom: "E-mails", description: "Demandes entrantes", statut: "Connecté" },
      { nom: "WhatsApp", description: "Demandes rapides", statut: "Synchronisation nécessaire" },
      { nom: "Fichiers Excel", description: "Listes de références", statut: "Connecté" },
      { nom: "Site web", description: "Formulaire de demande", statut: "Connecté" },
    ],
    questionsSuggerees: [
      "Prépare un brouillon de devis pour 12 tôles Hardox 450 8 mm",
      "Vérifie la disponibilité de la référence IN-304-T20",
      "Quelle remise appliquer à un client Grand compte pour un devis > 50 000 € ?",
    ],
    reponseTest: {
      question: "Prépare un brouillon de devis pour 12 tôles Hardox 450 8 mm",
      contenu: [
        "Devis DEV-2026-142 préparé pour MetalCorp SAS",
        "Ligne : Hardox 450 8 mm, 2000×6000, qté 12, PU 1 040 €",
        "Remise : 3 % (grille Grand compte)",
        "Sous-total HT : 12 105 € · TVA 20 % : 2 421 € · Total TTC : 14 526 €",
        "Paiement 30 j fin de mois · Livraison 7 j ouvrés",
      ],
      sourcesUsed: ["Catalogue tarifaire 2026", "Remises autorisées", "Délais de livraison"],
      confiance: 91,
      manquantes: ["Adresse de livraison exacte"],
      actions: ["Envoyer au commercial", "Générer le PDF"],
    },
  },
  {
    id: "stocks",
    nom: "Agent de gestion des stocks",
    icon: Package,
    description: "Surveille les niveaux de stock et anticipe les ruptures.",
    mission: "Maintenir la disponibilité des produits et alerter en amont des ruptures potentielles.",
    service: "Logistique",
    statut: "Actif",
    sourcesCount: 5,
    docsCount: 24,
    maj: "24/07/2026",
    responsable: "M. Girard",
    readiness: 95,
    autonomie: "Actions automatiques limitées",
    langue: "Français",
    ton: "Concis et opérationnel",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Créer une alerte", enabled: true },
      { label: "Proposer une recommandation", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Générer un rapport", enabled: true },
    ],
    instructions:
      "Comparer chaque référence à son seuil minimum. Prendre en compte les commandes en cours et les mouvements des 30 derniers jours. Émettre une alerte dès qu'un risque de rupture est détecté dans un délai de couverture < 15 jours. Proposer une quantité de réapprovisionnement cohérente avec la consommation moyenne.",
    obligatoires: ["Référence", "Quantité disponible", "Emplacement", "Seuil minimum", "Consommation moyenne"],
    restrictions: [
      "Ne pas déclencher automatiquement un ordre d'achat sans validation",
      "Signaler les incohérences de stock",
      "Ne pas modifier les seuils sans validation",
    ],
    connaissances: [
      { nom: "Catalogue des références", type: "Excel", categorie: "Catalogue produit", date: "05/01/2026", maj: "22/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Quantités disponibles", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Emplacements entrepôt", type: "Excel", categorie: "Procédure interne", date: "10/02/2026", maj: "15/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Seuils de stock", type: "Excel", categorie: "Procédure interne", date: "12/03/2026", maj: "20/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Mouvements de stock", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Privée" },
    ],
    sources: [
      { nom: "ERP", description: "Stocks temps réel", statut: "Connecté" },
      { nom: "Historique des commandes", description: "Commandes fournisseurs", statut: "Connecté" },
      { nom: "Fichiers Excel", description: "Inventaires manuels", statut: "Connecté" },
      { nom: "Documents internes", description: "Procédures logistiques", statut: "Connecté" },
      { nom: "Base fournisseurs", description: "Délais de livraison", statut: "Synchronisation nécessaire" },
    ],
    questionsSuggerees: [
      "Quelles références sont en risque de rupture cette semaine ?",
      "Suggère un réapprovisionnement pour les inox 304",
      "Quelle est la couverture stock actuelle des tôles Hardox ?",
    ],
    reponseTest: {
      question: "Quelles références sont en risque de rupture cette semaine ?",
      contenu: [
        "3 références sous seuil : HX-450-P08, IN-304-T20, AC-S355-B25",
        "Couverture estimée : 6 j / 9 j / 4 j",
        "Recommandation : lancer une commande de réapprovisionnement sous 48 h",
      ],
      sourcesUsed: ["Quantités disponibles", "Seuils de stock", "Mouvements de stock"],
      confiance: 94,
      manquantes: [],
      actions: ["Créer une alerte", "Proposer un ordre d'achat"],
    },
  },
  {
    id: "achats",
    nom: "Agent achats et approvisionnement",
    icon: ShoppingBag,
    description: "Compare les fournisseurs et prépare les commandes d'approvisionnement.",
    mission: "Optimiser les achats en comparant les fournisseurs sur prix, délais et fiabilité.",
    service: "Achats",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 37,
    maj: "22/07/2026",
    responsable: "M. Rossi",
    readiness: 85,
    autonomie: "Validation humaine obligatoire",
    langue: "Français",
    ton: "Analytique",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Proposer une recommandation", enabled: true },
      { label: "Générer un rapport", enabled: true },
      { label: "Créer une alerte", enabled: true },
    ],
    instructions:
      "Pour chaque besoin d'approvisionnement, comparer au minimum trois fournisseurs sur le prix, le délai, les conditions de paiement et l'évaluation historique. Proposer le fournisseur le plus adapté en justifiant le choix. Signaler tout écart de prix supérieur à 10 % par rapport à l'historique.",
    obligatoires: ["Référence à commander", "Quantité", "Délai souhaité", "Budget indicatif", "Fournisseurs consultés"],
    restrictions: [
      "Ne pas passer commande sans validation acheteur",
      "Ne pas contourner les fournisseurs référencés",
      "Signaler les fournisseurs non évalués",
    ],
    connaissances: [
      { nom: "Liste des fournisseurs", type: "Excel", categorie: "Historique commercial", date: "05/01/2026", maj: "18/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Catalogues fournisseurs", type: "PDF", categorie: "Catalogue produit", date: "02/02/2026", maj: "12/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Historique des prix", type: "Excel", categorie: "Historique commercial", date: "01/01/2026", maj: "22/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Délais moyens", type: "Excel", categorie: "Données ERP fictives", date: "10/03/2026", maj: "20/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Conditions de paiement", type: "PDF", categorie: "Procédure interne", date: "12/04/2026", maj: "12/04/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Évaluations fournisseurs", type: "Excel", categorie: "Procédure interne", date: "15/05/2026", maj: "15/07/2026", statut: "À vérifier", partage: "Privée" },
    ],
    sources: [
      { nom: "ERP", description: "Commandes et historique", statut: "Connecté" },
      { nom: "Base fournisseurs", description: "Contacts et évaluations", statut: "Connecté" },
      { nom: "E-mails", description: "Offres fournisseurs", statut: "Connecté" },
      { nom: "Documents internes", description: "Procédures achats", statut: "Connecté" },
      { nom: "Fichiers Excel", description: "Tableaux comparatifs", statut: "Connecté" },
      { nom: "Site web", description: "Portails fournisseurs", statut: "Non connecté" },
    ],
    questionsSuggerees: [
      "Quel fournisseur choisir pour 5 tonnes d'inox 304 ?",
      "Compare les délais moyens des trois principaux fournisseurs acier",
      "Alerte-moi sur les fournisseurs dont les délais dérivent",
    ],
    reponseTest: {
      question: "Quel fournisseur choisir pour 5 tonnes d'inox 304 ?",
      contenu: [
        "Recommandation : Fournisseur A (prix -4 % vs. moyenne)",
        "Délai : 12 j vs. 15 j moyenne",
        "Évaluation : 4,6 / 5",
        "Alternative : Fournisseur C si urgence < 10 j",
      ],
      sourcesUsed: ["Liste des fournisseurs", "Historique des prix", "Délais moyens"],
      confiance: 89,
      manquantes: ["Adresse de livraison finale"],
      actions: ["Préparer la commande", "Envoyer une consultation"],
    },
  },
  {
    id: "sc",
    nom: "Agent service client omnicanal",
    icon: MessageSquare,
    description: "Répond aux demandes clients sur tous les canaux avec cohérence.",
    mission: "Fournir une réponse rapide et cohérente aux clients, quel que soit le canal utilisé.",
    service: "Service client",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 28,
    maj: "24/07/2026",
    responsable: "Mme Petit",
    readiness: 90,
    autonomie: "Validation humaine obligatoire",
    langue: "Français",
    ton: "Courtois et professionnel",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Générer une réponse", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Transférer une demande", enabled: true },
      { label: "Créer une alerte", enabled: true },
    ],
    instructions:
      "Répondre aux messages entrants en s'appuyant sur la FAQ, l'ERP et l'historique client. Proposer une réponse structurée : accusé de réception, réponse claire, prochaine étape. Ne jamais promettre un délai sans vérification. Escalader toute demande complexe ou insatisfaction manifeste.",
    obligatoires: ["Nom du client", "Numéro de commande éventuel", "Canal", "Type de demande"],
    restrictions: [
      "Ne pas répondre en dehors du périmètre autorisé",
      "Ne pas promettre un remboursement sans validation",
      "Toujours indiquer si un humain reprend la conversation",
    ],
    connaissances: [
      { nom: "FAQ SERIMA", type: "Word", categorie: "FAQ", date: "10/01/2026", maj: "20/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Catalogue produit", type: "PDF", categorie: "Catalogue produit", date: "12/01/2026", maj: "20/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Disponibilités", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Délais standard", type: "Excel", categorie: "Procédure interne", date: "18/03/2026", maj: "18/03/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Procédures de réponse", type: "Word", categorie: "Procédure interne", date: "05/04/2026", maj: "10/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Informations commandes", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Privée" },
    ],
    sources: [
      { nom: "E-mails", description: "Boîte support", statut: "Connecté" },
      { nom: "WhatsApp", description: "Messagerie client", statut: "Connecté" },
      { nom: "CRM", description: "Fiches et historique", statut: "Connecté" },
      { nom: "ERP", description: "Commandes et stocks", statut: "Connecté" },
      { nom: "Site web", description: "Formulaire contact", statut: "Connecté" },
      { nom: "Documents internes", description: "Procédures", statut: "Connecté" },
    ],
    questionsSuggerees: [
      "Où en est ma commande CMD-2026-034 ?",
      "Le produit Hardox 450 8 mm est-il en stock ?",
      "Quelle procédure pour retourner un produit ?",
    ],
    reponseTest: {
      question: "Où en est ma commande CMD-2026-034 ?",
      contenu: [
        "Bonjour, votre commande CMD-2026-034 est en préparation à Lyon.",
        "Expédition prévue : 25/07/2026",
        "Transporteur : DB Schenker · Suivi disponible dès l'expédition",
      ],
      sourcesUsed: ["Informations commandes", "Délais standard", "Procédures de réponse"],
      confiance: 92,
      manquantes: [],
      actions: ["Envoyer la réponse", "Notifier le commercial"],
    },
  },
  {
    id: "doc",
    nom: "Agent documentaire et qualité",
    icon: FileCheck,
    description: "Analyse et valide les documents techniques et qualité.",
    mission: "Garantir la conformité et l'accessibilité des documents techniques et qualité.",
    service: "Qualité",
    statut: "Actif",
    sourcesCount: 5,
    docsCount: 58,
    maj: "21/07/2026",
    responsable: "Mme Marchand",
    readiness: 86,
    autonomie: "Suggestions uniquement",
    langue: "Français",
    ton: "Rigoureux",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Créer une alerte", enabled: true },
      { label: "Générer un rapport", enabled: true },
      { label: "Proposer une recommandation", enabled: true },
    ],
    instructions:
      "Vérifier la présence des documents obligatoires pour chaque produit livré (fiche technique, certificat matière, certificat de conformité). Signaler tout document manquant, expiré ou incohérent. Ne jamais valider un document sans revue humaine.",
    obligatoires: ["Référence produit", "N° lot", "Type de document", "Date d'émission"],
    restrictions: [
      "Ne pas modifier un document sans validation qualité",
      "Ne pas valider un certificat périmé",
      "Signaler toute anomalie détectée",
    ],
    connaissances: [
      { nom: "Fiches techniques", type: "PDF", categorie: "Fiche technique", date: "10/01/2026", maj: "18/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Certificats matière", type: "PDF", categorie: "Certificat", date: "20/02/2026", maj: "20/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Certificats de conformité", type: "PDF", categorie: "Certificat", date: "05/03/2026", maj: "12/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Procédures qualité", type: "Word", categorie: "Procédure interne", date: "02/01/2026", maj: "01/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Rapports de contrôle", type: "PDF", categorie: "Procédure interne", date: "15/05/2026", maj: "20/07/2026", statut: "En traitement", partage: "Privée" },
    ],
    sources: [
      { nom: "Documents internes", description: "Base documentaire qualité", statut: "Connecté" },
      { nom: "ERP", description: "Références et lots", statut: "Connecté" },
      { nom: "E-mails", description: "Réception de certificats", statut: "Connecté" },
      { nom: "Fichiers Excel", description: "Registres qualité", statut: "Connecté" },
      { nom: "Site web", description: "Portail certificats fournisseurs", statut: "Non connecté" },
    ],
    questionsSuggerees: [
      "Quels certificats manquent pour le lot L-2026-0142 ?",
      "La fiche technique de la référence HX-450-P08 est-elle à jour ?",
      "Génère un rapport de conformité pour la commande CMD-2026-041",
    ],
    reponseTest: {
      question: "Quels certificats manquent pour le lot L-2026-0142 ?",
      contenu: [
        "Certificat matière : présent",
        "Certificat de conformité : absent",
        "Rapport de contrôle : absent",
        "Recommandation : demander les certificats manquants au fournisseur A",
      ],
      sourcesUsed: ["Certificats matière", "Certificats de conformité", "Procédures qualité"],
      confiance: 90,
      manquantes: ["Date de réception du lot"],
      actions: ["Créer une alerte qualité", "Envoyer une demande au fournisseur"],
    },
  },
  {
    id: "prospection",
    nom: "Agent de prospection B2B",
    icon: Users,
    description: "Aide les commerciaux à identifier et contacter des cibles.",
    mission: "Alimenter la démarche commerciale avec des cibles qualifiées et des messages adaptés.",
    service: "Développement commercial",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 22,
    maj: "20/07/2026",
    responsable: "M. Dubois",
    readiness: 78,
    autonomie: "Suggestions uniquement",
    langue: "Français",
    ton: "Engageant",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Générer une réponse", enabled: true },
      { label: "Proposer une recommandation", enabled: true },
      { label: "Générer un rapport", enabled: false },
    ],
    instructions:
      "À partir des secteurs cibles et des argumentaires, préparer un script d'entrée en matière personnalisé par entreprise. Croiser avec l'historique CRM pour éviter les doublons. Toujours proposer une prochaine action concrète.",
    obligatoires: ["Secteur cible", "Zone géographique", "Taille d'entreprise", "Enjeu identifié"],
    restrictions: [
      "Ne pas envoyer un message commercial sans validation",
      "Respecter le RGPD sur les données récoltées",
      "Ne pas contacter un client en portefeuille sans l'accord du commercial",
    ],
    connaissances: [
      { nom: "Secteurs ciblés", type: "Word", categorie: "Procédure interne", date: "10/02/2026", maj: "10/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Argumentaires commerciaux", type: "Word", categorie: "Procédure interne", date: "05/03/2026", maj: "12/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Catalogue produit", type: "PDF", categorie: "Catalogue produit", date: "12/01/2026", maj: "20/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Scripts d'appel", type: "Word", categorie: "Procédure interne", date: "08/04/2026", maj: "08/04/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Modèles d'e-mails", type: "Word", categorie: "Procédure interne", date: "15/05/2026", maj: "18/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Profils cibles", type: "Excel", categorie: "Historique commercial", date: "01/06/2026", maj: "20/07/2026", statut: "En traitement", partage: "Privée" },
    ],
    sources: [
      { nom: "CRM", description: "Fiches entreprises", statut: "Connecté" },
      { nom: "E-mails", description: "Envoi de campagnes", statut: "Connecté" },
      { nom: "Site web", description: "Sources externes", statut: "Non connecté" },
      { nom: "Documents internes", description: "Argumentaires", statut: "Connecté" },
      { nom: "Fichiers Excel", description: "Listes cibles", statut: "Connecté" },
      { nom: "Historique des commandes", description: "Références existantes", statut: "Connecté" },
    ],
    questionsSuggerees: [
      "Suggère 5 cibles dans la métallurgie en Rhône-Alpes",
      "Rédige un e-mail d'entrée pour un directeur achats du BTP",
      "Quels arguments mettre en avant pour l'inox 316L alimentaire ?",
    ],
    reponseTest: {
      question: "Suggère 5 cibles dans la métallurgie en Rhône-Alpes",
      contenu: [
        "MécaLyon SAS · Villeurbanne · 120 salariés",
        "Aciérie Grenoble · Grenoble · 240 salariés",
        "Steel Rhône · Saint-Étienne · 80 salariés",
        "Tôlerie Alpine · Chambéry · 55 salariés",
        "MetalPro 69 · Lyon · 190 salariés",
      ],
      sourcesUsed: ["Profils cibles", "Secteurs ciblés", "Argumentaires commerciaux"],
      confiance: 74,
      manquantes: ["Interlocuteurs nommés", "Historique de contact"],
      actions: ["Préparer une campagne e-mail", "Assigner à un commercial"],
    },
  },
  {
    id: "suivi",
    nom: "Agent de suivi des commandes et livraisons",
    icon: Truck,
    description: "Suit les étapes de préparation, expédition et livraison.",
    mission: "Assurer la visibilité sur chaque commande et anticiper les retards.",
    service: "Logistique",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 19,
    maj: "24/07/2026",
    responsable: "M. Vidal",
    readiness: 91,
    autonomie: "Actions automatiques limitées",
    langue: "Français",
    ton: "Direct",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Créer une alerte", enabled: true },
      { label: "Générer une réponse", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Générer un rapport", enabled: true },
    ],
    instructions:
      "Suivre chaque commande depuis la validation jusqu'à la livraison. Détecter tout écart par rapport au planning prévu (préparation, transport, réception). Notifier proactivement le service client en cas de risque supérieur à 24 h.",
    obligatoires: ["N° commande", "Client", "Étape en cours", "Date prévue"],
    restrictions: [
      "Ne pas modifier une date planifiée sans validation",
      "Ne pas contacter directement un transporteur sans consigne",
      "Signaler toute anomalie de tracking",
    ],
    connaissances: [
      { nom: "Commandes en cours", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Étapes de préparation", type: "Word", categorie: "Procédure interne", date: "10/02/2026", maj: "15/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Délais logistiques", type: "Excel", categorie: "Procédure interne", date: "05/03/2026", maj: "15/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Transporteurs", type: "Excel", categorie: "Historique commercial", date: "12/04/2026", maj: "20/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Procédures d'expédition", type: "Word", categorie: "Procédure interne", date: "18/05/2026", maj: "18/05/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Règles de notification", type: "Word", categorie: "Procédure interne", date: "01/06/2026", maj: "10/07/2026", statut: "Disponible", partage: "Privée" },
    ],
    sources: [
      { nom: "ERP", description: "Commandes et statuts", statut: "Connecté" },
      { nom: "CRM", description: "Client et contacts", statut: "Connecté" },
      { nom: "E-mails", description: "Confirmations transporteur", statut: "Connecté" },
      { nom: "WhatsApp", description: "Notifications rapides", statut: "Synchronisation nécessaire" },
      { nom: "Site web", description: "Portail tracking", statut: "Connecté" },
      { nom: "Historique des commandes", description: "Historique de livraison", statut: "Connecté" },
    ],
    questionsSuggerees: [
      "Quelles commandes risquent d'être en retard cette semaine ?",
      "Où en est la commande CMD-2026-041 ?",
      "Combien de commandes livrées à l'heure ce mois-ci ?",
    ],
    reponseTest: {
      question: "Quelles commandes risquent d'être en retard cette semaine ?",
      contenu: [
        "3 commandes à risque : CMD-2026-041, CMD-2026-052, CMD-2026-060",
        "Cause principale : transporteur B saturé",
        "Recommandation : notifier les clients concernés dès aujourd'hui",
      ],
      sourcesUsed: ["Commandes en cours", "Délais logistiques", "Transporteurs"],
      confiance: 88,
      manquantes: [],
      actions: ["Créer une alerte", "Préparer les messages clients"],
    },
  },
  {
    id: "sav",
    nom: "Agent réclamations et SAV",
    icon: AlertTriangle,
    description: "Qualifie, priorise et suit les réclamations clients.",
    mission: "Traiter les réclamations avec efficacité et cohérence pour préserver la satisfaction client.",
    service: "Service après-vente",
    statut: "Actif",
    sourcesCount: 5,
    docsCount: 26,
    maj: "23/07/2026",
    responsable: "Mme Roche",
    readiness: 83,
    autonomie: "Validation humaine obligatoire",
    langue: "Français",
    ton: "Empathique et professionnel",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Générer une réponse", enabled: true },
      { label: "Transférer une demande", enabled: true },
      { label: "Créer une alerte", enabled: true },
      { label: "Générer un rapport", enabled: true },
    ],
    instructions:
      "Classer chaque réclamation par catégorie et gravité. Vérifier la garantie applicable. Proposer une solution parmi celles autorisées. Escalader systématiquement les cas graves ou récurrents.",
    obligatoires: ["Client", "N° commande", "Catégorie", "Description", "Photo ou preuve éventuelle"],
    restrictions: [
      "Ne pas engager un geste commercial sans validation",
      "Ne pas clôturer un ticket sans confirmation client",
      "Ne pas contourner la procédure SAV",
    ],
    connaissances: [
      { nom: "Procédures SAV", type: "Word", categorie: "Procédure interne", date: "05/01/2026", maj: "18/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Catégories de réclamation", type: "Excel", categorie: "Procédure interne", date: "10/02/2026", maj: "10/02/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Conditions de garantie", type: "PDF", categorie: "Procédure interne", date: "12/03/2026", maj: "12/07/2026", statut: "Disponible", partage: "Générale" },
      { nom: "Solutions autorisées", type: "Word", categorie: "Procédure interne", date: "05/04/2026", maj: "15/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Historique des incidents", type: "Excel", categorie: "Historique commercial", date: "01/05/2026", maj: "20/07/2026", statut: "Disponible", partage: "Partagée" },
    ],
    sources: [
      { nom: "E-mails", description: "Réclamations reçues", statut: "Connecté" },
      { nom: "WhatsApp", description: "Réclamations rapides", statut: "Connecté" },
      { nom: "CRM", description: "Historique client", statut: "Connecté" },
      { nom: "ERP", description: "Commandes et lots", statut: "Connecté" },
      { nom: "Documents internes", description: "Procédures SAV", statut: "Connecté" },
    ],
    questionsSuggerees: [
      "Quelle solution proposer pour un défaut d'aspect sur une tôle Hardox ?",
      "Combien de réclamations ouvertes ce mois-ci ?",
      "Y a-t-il un incident récurrent sur le fournisseur B ?",
    ],
    reponseTest: {
      question: "Quelle solution proposer pour un défaut d'aspect sur une tôle Hardox ?",
      contenu: [
        "Catégorie : Défaut d'aspect · Gravité : Moyenne",
        "Garantie applicable : oui (30 jours)",
        "Solution proposée : avoir partiel de 8 % ou remplacement sous 10 j",
        "Escalade nécessaire au responsable SAV avant validation",
      ],
      sourcesUsed: ["Procédures SAV", "Conditions de garantie", "Solutions autorisées"],
      confiance: 82,
      manquantes: ["Photo du défaut"],
      actions: ["Demander une photo au client", "Créer le ticket SAV"],
    },
  },
  {
    id: "reporting",
    nom: "Agent reporting et pilotage",
    icon: BarChart3,
    description: "Génère les tableaux de bord et synthèses de pilotage.",
    mission: "Fournir aux dirigeants une vision claire et à jour de la performance de l'entreprise.",
    service: "Direction générale",
    statut: "Actif",
    sourcesCount: 6,
    docsCount: 16,
    maj: "24/07/2026",
    responsable: "M. Morel",
    readiness: 89,
    autonomie: "Suggestions uniquement",
    langue: "Français",
    ton: "Synthétique",
    actions: [
      { label: "Analyser les demandes", enabled: true },
      { label: "Consulter les documents", enabled: true },
      { label: "Générer un rapport", enabled: true },
      { label: "Créer une alerte", enabled: true },
      { label: "Proposer une recommandation", enabled: true },
    ],
    instructions:
      "Produire chaque semaine une synthèse commerciale, logistique et qualité. Croiser les données de ventes, stocks, commandes et réclamations. Signaler les écarts significatifs par rapport aux objectifs.",
    obligatoires: ["Période analysée", "Périmètre", "Indicateurs demandés"],
    restrictions: [
      "Ne pas publier un rapport sans validation direction",
      "Ne pas diffuser des données confidentielles hors périmètre",
      "Toujours indiquer la source des chiffres",
    ],
    connaissances: [
      { nom: "Indicateurs commerciaux", type: "Excel", categorie: "Procédure interne", date: "05/01/2026", maj: "22/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Données de ventes", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Privée" },
      { nom: "Stocks agrégés", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Commandes", type: "Données ERP fictives", categorie: "Données ERP fictives", date: "01/07/2026", maj: "24/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Réclamations", type: "Excel", categorie: "Historique commercial", date: "01/06/2026", maj: "20/07/2026", statut: "Disponible", partage: "Partagée" },
      { nom: "Objectifs de performance", type: "Excel", categorie: "Procédure interne", date: "02/01/2026", maj: "02/01/2026", statut: "Disponible", partage: "Privée" },
    ],
    sources: [
      { nom: "ERP", description: "Ventes, stocks, commandes", statut: "Connecté" },
      { nom: "CRM", description: "Pipeline commercial", statut: "Connecté" },
      { nom: "Fichiers Excel", description: "Objectifs internes", statut: "Connecté" },
      { nom: "Documents internes", description: "Modèles de rapports", statut: "Connecté" },
      { nom: "Historique des commandes", description: "Volumes historiques", statut: "Connecté" },
      { nom: "Base fournisseurs", description: "Performance amont", statut: "Synchronisation nécessaire" },
    ],
    questionsSuggerees: [
      "Résume la semaine commerciale écoulée",
      "Compare le CA vs. objectif mensuel",
      "Quelles familles produits sont en croissance ce trimestre ?",
    ],
    reponseTest: {
      question: "Résume la semaine commerciale écoulée",
      contenu: [
        "CA semaine : 412 k€ (+6 % vs. S-1)",
        "Marge moyenne : 22,4 %",
        "3 commandes majeures signées",
        "2 réclamations ouvertes, aucune critique",
        "Alerte : stock IN-304-T20 sous seuil",
      ],
      sourcesUsed: ["Données de ventes", "Objectifs de performance", "Réclamations"],
      confiance: 90,
      manquantes: [],
      actions: ["Diffuser la synthèse", "Créer une alerte stock"],
    },
  },
];

export const HISTORIQUE = [
  { date: "24/07/2026 14:22", agent: "Agent de gestion des stocks", modification: "Ajout du catalogue des références", user: "admin@serima.fr", statut: "Validé" },
  { date: "24/07/2026 10:05", agent: "Agent de traitement des devis", modification: "Modification des instructions", user: "m.bernard@serima.fr", statut: "Validé" },
  { date: "23/07/2026 17:48", agent: "Agent de suivi des commandes", modification: "Activation de l'accès aux commandes", user: "admin@serima.fr", statut: "Validé" },
  { date: "23/07/2026 09:12", agent: "Agent achats et approvisionnement", modification: "Mise à jour des conditions commerciales", user: "p.rossi@serima.fr", statut: "Validé" },
  { date: "22/07/2026 16:30", agent: "Agent documentaire et qualité", modification: "Désactivation d'un document obsolète", user: "s.marchand@serima.fr", statut: "Validé" },
  { date: "22/07/2026 11:04", agent: "Agent technico-commercial", modification: "Ajout de la fiche technique anti-abrasion", user: "admin@serima.fr", statut: "Validé" },
  { date: "21/07/2026 15:20", agent: "Agent réclamations et SAV", modification: "Ajustement des solutions autorisées", user: "c.roche@serima.fr", statut: "En attente" },
];
