/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as ReclamationsRouteImport } from './routes/reclamations'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DemandesRouteImport } from './routes/demandes'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamationsRoute = ReclamationsRouteImport.update({
  id: '/reclamations',
  path: '/reclamations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesRoute = DemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/commandes': typeof CommandesRoute
  '/demandes': typeof DemandesRoute
  '/devis': typeof DevisRoute
  '/documents': typeof DocumentsRoute
  '/reclamations': typeof ReclamationsRoute
  '/reporting': typeof ReportingRoute
  '/stocks': typeof StocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/commandes': typeof CommandesRoute
  '/demandes': typeof DemandesRoute
  '/devis': typeof DevisRoute
  '/documents': typeof DocumentsRoute
  '/reclamations': typeof ReclamationsRoute
  '/reporting': typeof ReportingRoute
  '/stocks': typeof StocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/commandes': typeof CommandesRoute
  '/demandes': typeof DemandesRoute
  '/devis': typeof DevisRoute
  '/documents': typeof DocumentsRoute
  '/reclamations': typeof ReclamationsRoute
  '/reporting': typeof ReportingRoute
  '/stocks': typeof StocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/commandes'
    | '/demandes'
    | '/devis'
    | '/documents'
    | '/reclamations'
    | '/reporting'
    | '/stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/commandes'
    | '/demandes'
    | '/devis'
    | '/documents'
    | '/reclamations'
    | '/reporting'
    | '/stocks'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/commandes'
    | '/demandes'
    | '/devis'
    | '/documents'
    | '/reclamations'
    | '/reporting'
    | '/stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  CommandesRoute: typeof CommandesRoute
  DemandesRoute: typeof DemandesRoute
  DevisRoute: typeof DevisRoute
  DocumentsRoute: typeof DocumentsRoute
  ReclamationsRoute: typeof ReclamationsRoute
  ReportingRoute: typeof ReportingRoute
  StocksRoute: typeof StocksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamations': {
      id: '/reclamations'
      path: '/reclamations'
      fullPath: '/reclamations'
      preLoaderRoute: typeof ReclamationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes': {
      id: '/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof DemandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  CommandesRoute: CommandesRoute,
  DemandesRoute: DemandesRoute,
  DevisRoute: DevisRoute,
  DocumentsRoute: DocumentsRoute,
  ReclamationsRoute: ReclamationsRoute,
  ReportingRoute: ReportingRoute,
  StocksRoute: StocksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
